spring.application.name=spring-demo

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/delivery_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:aze}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.open-in-view=false

# Pagination
spring.data.web.pageable.default-page-size=10

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# JWT
app.jwt.secret=${JWT_SECRET:my-super-secret-key-that-is-long-enough-for-hmac-sha256-algorithm}
app.jwt.expiration=${JWT_EXPIRATION:604800000}

# Frontend URL — used in email links
app.frontend.url=${FRONTEND_URL:http://localhost:3000}

# Mail
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:haxerdz00@gmail.com}
spring.mail.password=${MAIL_PASSWORD:rzuwtgqwbnbjazim}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000


# Disable mail auto-config if no credentials provided
spring.mail.test-connection=false